import React from 'react';
import { FAQItem } from './FAQItem';

export function FAQSection() {
  const faqs = [
    {
      question: "What content sources can I use with AutoWP?",
      answer: "AutoWP can fetch content from RSS feeds, WordPress sites, and Google News. Our system automatically pulls the latest content from your sources, processes it through spam and similarity filters, and then analyzes the filtered content to create COMPLETELY NEW content following your desired schema. This results in 100% unique, SEO-optimized content that matches your specifications perfectly."
    },
    {
      question: "What is the AI Agent and how does it work?",
      answer: "The AI Agent is a fully automated assistant that can conduct internet research based on user-defined instructions. Unlike RSS, WordPress, or Google News sources that follow a fixed context, the AI Agent works like a real person - it can scan multiple sources, follow your specific instructions, and generate content using either your custom schema or our default templates. It's like having a dedicated research assistant working 24/7!"
    },
    {
      question: "Is the generated content SEO-friendly?",
      answer: "Absolutely! Content generated by AutoWP consistently receives high scores from tools like RankMath and Yoast! Our AI agents automatically identify high-search-volume, low-competition keywords relevant to your content and incorporate them naturally. This ensures your content is not just unique but also 100% SEO-optimized for maximum visibility!"
    },
    {
      question: "How does AutoWP ensure content quality?",
      answer: "AutoWP uses advanced AI models to generate and optimize content. Each piece goes through multiple quality checks including spam detection, plagiarism checking, and SEO optimization to ensure high-quality, unique content every time."
    },
    {
      question: "Can I customize the content generation process?",
      answer: "Yes! AutoWP offers full customization through the Content Planner. You can define HTML structure, create custom prompts, and use dynamic templates to control exactly how your content is generated."
    },
    {
      question: "How often can AutoWP generate content?",
      answer: "You can schedule content generation hourly, daily (once or twice), or weekly. The frequency can be easily adjusted in your dashboard settings to match your content needs."
    },
    {
      question: "How does the automatic image generation work?",
      answer: "AutoWP offers two options for images: AI-generated images using Flux and Stable Diffusion for unique visuals, or real images sourced through DuckDuckGo image search. You can choose which method works best for your content."
    },
    {
      question: "Is there a free trial available?",
      answer: "Yes! Our free plan includes 5 AI content generations and 5 AI image generations, allowing you to experience AutoWP's capabilities before upgrading to a paid plan."
    },
    {
      question: "Can I cancel my subscription anytime?",
      answer: "Yes! You can easily cancel, pause, upgrade, or downgrade your subscription at any time through your dashboard. We believe in flexibility and making sure you have control over your subscription."
    }
  ];

  return (
    <section className="py-24 bg-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-gray-900 mb-4">Frequently Asked Questions</h2>
          <p className="text-xl text-gray-600">Everything you need to know about AutoWP</p>
        </div>
        
        <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-lg">
          {faqs.map((faq, index) => (
            <FAQItem
              key={index}
              question={faq.question}
              answer={faq.answer}
            />
          ))}
        </div>

        <div className="text-center mt-12">
          <p className="text-gray-600 mb-4">Still have questions?</p>
          <a 
            href="#contact" 
            className="text-[#00749c] font-medium hover:text-[#005d7d] transition-colors"
          >
            Contact our support team
          </a>
        </div>
      </div>
    </section>
  );
}